---
permalink: performance-checker/concept_set_up_graphite_to_receive_performance_data.html 
sidebar: sidebar 
keywords: setting, graphite, receive, performance, data, unified manager 
summary: Graphit ist ein offenes Software-Tool zum Erfassen und Darstellen von Performancedaten aus Computersystemen. Ihr Graphite-Server und Ihre Software müssen richtig konfiguriert sein, um statistische Daten von Unified Manager zu erhalten. 
---
= Einrichten von Graphite für den Empfang von Leistungsdaten von Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Graphit ist ein offenes Software-Tool zum Erfassen und Darstellen von Performancedaten aus Computersystemen. Ihr Graphite-Server und Ihre Software müssen richtig konfiguriert sein, um statistische Daten von Unified Manager zu erhalten.

NetApp testet und verifiziert keine bestimmten Versionen von Graphite oder anderen Tools von Drittanbietern.


NOTE: Der Graphite-Server empfängt keine Performance-Daten für Volumes von Unified Manager.

Nachdem Sie Graphite gemäß den Installationsanweisungen installiert haben, müssen Sie zur Unterstützung der statistischen Datenübertragung von Unified Manager folgende Änderungen vornehmen:

* In der `/opt/graphite/conf/carbon.conf` Datei muss die maximale Anzahl von Dateien, die pro Minute auf dem Graphite-Server erstellt werden können(`*MAX_CREATES_PER_MINUTE = 200*`, auf _200_ gesetzt werden.
+
Abhängig von der Anzahl der Cluster in Ihrer Konfiguration und den zu sendenden Statistikobjekten können Tausende neue Dateien erstellt werden, die zunächst erstellt werden müssen. Bei 200 Dateien pro Minute dauert es möglicherweise 15 Minuten oder länger, bevor alle metrischen Dateien ursprünglich erstellt werden. Nachdem alle eindeutigen metrischen Dateien erstellt wurden, ist dieser Parameter nicht mehr relevant.

* Wenn Sie Graphite auf einem Server ausführen, der über eine IPv6-Adresse bereitgestellt wird, muss der Wert für LINE_RECEIVER_INTERFACE in der `/opt/graphite/conf/carbon.conf` Datei von „`0.0.0.0`“ in „`:`“ geändert werden(`*LINE_RECEIVER_INTERFACE = ::*`.
* In der `/opt/graphite/conf/storage-schemas.conf` Datei muss der `retentions` Parameter verwendet werden, um die Frequenz auf 5 Minuten und die Aufbewahrungsfrist auf die Anzahl der Tage einzustellen, die für Ihre Umgebung relevant sind.
+
Die Aufbewahrungsdauer kann so lange betragen, wie Ihre Umgebung es zulässt, aber der Frequenzwert muss für mindestens eine Aufbewahrungseinstellung auf 5 Minuten eingestellt sein. Im folgenden Beispiel wird für Unified Manager mithilfe des Parameters ein Abschnitt definiert `pattern`, und durch die Werte wird die initiale Frequenz auf 5 Minuten und die Aufbewahrungsfrist auf 100 Tage festgelegt: `*[OPM]*`

+
`*pattern = ^netapp-performance\..*`

+
`*retentions = 5m:100d*`

+
[NOTE]
====
Wenn das Standard-Hersteller-Tag von „`NetApp-Performance`“ zu einem anderen geändert wird, muss diese Änderung auch im Parameter widergespiegelt werden `pattern`.

====


[NOTE]
====
Wenn der Graphite-Server nicht verfügbar ist, wenn der Unified Manager-Server versucht, Leistungsdaten zu senden, werden die Daten nicht gesendet und es besteht eine Lücke in den gesammelten Daten.

====