---
permalink: performance-checker/concept_metrocluster_configuration_verification.html 
sidebar: sidebar 
keywords: metrocluster, configuration, verification 
summary: Sie können Performance-Probleme bei gespiegelten Workloads in einer MetroCluster-Konfiguration vermeiden, indem Sie sicherstellen, dass die MetroCluster-Konfiguration korrekt eingerichtet ist. Sie können außerdem die Workload-Performance verbessern, indem Sie die Konfiguration ändern oder Software- oder Hardware-Komponenten aktualisieren. 
---
= Überprüfung der MetroCluster-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Performance-Probleme bei gespiegelten Workloads in einer MetroCluster over FC- und IP-Konfiguration vermeiden, indem Sie sicherstellen, dass die MetroCluster-Konfiguration korrekt eingerichtet ist. Sie können außerdem die Workload-Performance verbessern, indem Sie die Konfiguration ändern oder Software- oder Hardware-Komponenten aktualisieren.

Anweisungen zum Einrichten der Cluster in der MetroCluster-Konfiguration, einschließlich der Fibre Channel-Switches (FC), Kabel und Inter-Switch-Links (ISLs), finden Sie unter https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster-Dokumentation"]. Darüber hinaus unterstützt Sie die Konfiguration der MetroCluster Software, sodass die lokalen und Remote Cluster mit gespiegelten Volume-Daten kommunizieren können. Informationen zu Ihrem MetroCluster-over-IP-Setup finden Sie unter https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installieren Sie eine MetroCluster IP-Konfiguration"].

Sie können Ihre MetroCluster-Konfiguration mit den Anforderungen in vergleichen https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster-Dokumentation"], um zu ermitteln, ob ein Ändern oder Aktualisieren von Komponenten Ihrer MetroCluster-Konfiguration die Workload-Performance verbessern könnte. Dieser Vergleich hilft Ihnen bei der Beantwortung der folgenden Fragen:

* Sind die Controller für Ihre Workloads geeignet?
* Müssen Sie Ihre ISL-Bundles auf eine höhere Bandbreite aktualisieren, um einen höheren Durchsatz zu bewältigen?
* Können Sie die Buffer-to-Buffer Credits (BBC) auf Ihren Switches anpassen, um die Bandbreite zu erhöhen?
* Wenn Ihre Workloads einen hohen Schreibdurchsatz auf SSD-Storage (Solid State Drive) aufweisen, müssen Sie Ihre FC-to-SAS-Bridges aktualisieren, um den Durchsatz zu bewältigen?


*Verwandte Informationen*

* Informationen zum Austauschen oder Aktualisieren von MetroCluster-Komponenten finden Sie im https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster-Dokumentation"].
* Informationen zum Upgrade von Controllern finden Sie unter https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Upgrades von Controllern in einer MetroCluster FC-Konfiguration mithilfe von Switchover und Switchback"] und https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html["Upgrades von Controllern in einer MetroCluster IP-Konfiguration mithilfe von Switchover und Switchback"]

