---
permalink: storage-mgmt/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux host 
summary: 'Wenn Sie dem Verzeichnis nicht genügend Speicherplatz zur Unterstützung von Unified Manager zugewiesen `/opt/netapp/data` haben, wenn Sie den Linux-Host ursprünglich eingerichtet und Unified Manager dann installiert haben, können Sie nach der Installation Festplattenspeicher hinzufügen, indem Sie den Speicherplatz im Verzeichnis erhöhen `/opt/netapp/data`.' 
---
= Hinzufügen von Speicherplatz zum Datenverzeichnis des Linux-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie dem Verzeichnis nicht genügend Speicherplatz zur Unterstützung von Unified Manager zugewiesen `/opt/netapp/data` haben, wenn Sie den Linux-Host ursprünglich eingerichtet und Unified Manager dann installiert haben, können Sie nach der Installation Festplattenspeicher hinzufügen, indem Sie den Speicherplatz im Verzeichnis erhöhen `/opt/netapp/data`.

*Was Sie brauchen*

Sie müssen Root-Benutzerzugriff auf die Red hat Enterprise Linux oder CentOS Linux Maschine haben, auf der Unified Manager installiert ist.

Wir empfehlen, dass Sie ein Backup der Unified Manager-Datenbank erstellen, bevor Sie die Größe des Datenverzeichnisses vergrößern.

.Schritte
. Melden Sie sich als Root-Benutzer an dem Linux-Rechner an, auf dem Sie Speicherplatz hinzufügen möchten.
. Stoppen Sie den Unified Manager-Service und die zugehörige MySQL-Software in der angezeigten Reihenfolge: `systemctl stop ocieau ocie mysqld`
. Erstellen Sie einen temporären Sicherungsordner (z.B. ) mit ausreichend Speicherplatz, `/backup-data` um die Daten im aktuellen Verzeichnis zu enthalten `/opt/netapp/data`.
. Kopieren Sie den Inhalt und die Berechtigungskonfiguration des vorhandenen `/opt/netapp/data` Verzeichnisses in das Sicherungsdatenverzeichnis:
+
`cp -arp /opt/netapp/data/* /backup-data`

. Wenn SE Linux aktiviert ist:
+
.. Rufen Sie den SE Linux-Typ für Ordner im vorhandenen Ordner ab `/opt/netapp/data`:
+
`se_type=`ls -Z /opt/netapp/data| awk '{print $4}'| awk -F: '{print $3}'| head -1`

+
Das System gibt eine Bestätigung wie die folgende aus:

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. Führen Sie den Befehl aus `chcon`, um den SE Linux-Typ für das Backup-Verzeichnis festzulegen:
+
`chcon -R --type=mysqld_db_t /backup-data`



. Inhalt des Verzeichnisses entfernen `/opt/netapp/data`:
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. Erweitern Sie die Größe des `/opt/netapp/data` Verzeichnisses durch LVM-Befehle oder durch Hinzufügen zusätzlicher Festplatten auf mindestens 150 GB.
+
[NOTE]
====
Wenn Sie von einer Festplatte erstellt haben `/opt/netapp/data`, sollten Sie nicht versuchen, sie als NFS- oder CIFS-Freigabe zu mounten `/opt/netapp/data`. Denn wenn Sie in diesem Fall versuchen, den Speicherplatz zu erweitern, funktionieren einige LVM-Befehle, wie `resize` und, `extend` möglicherweise nicht wie erwartet.

====
. Bestätigen Sie, dass der `/opt/netapp/data` Verzeichniseigentümer (mysql) und die Gruppe (root) unverändert sind:
+
`ls -ltr /opt/netapp/ | grep data`

+
Das System gibt eine Bestätigung wie die folgende aus:

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. Wenn SE Linux aktiviert ist, bestätigen Sie, dass der Kontext für das `/opt/netapp/data` Verzeichnis weiterhin auf mysqld_db_t gesetzt ist:
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
Das System gibt eine Bestätigung wie die folgende aus:

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. Löschen Sie die Datei `abc`, damit diese externe Datei in Zukunft keinen Datenbankfehler verursacht.
. Kopieren Sie den Inhalt von `backup-data` zurück in das erweiterte `/opt/netapp/data` Verzeichnis:
+
`cp -arp /backup-data/* /opt/netapp/data/`

. Wenn SE Linux aktiviert ist, führen Sie den folgenden Befehl aus:
+
`chcon -R --type=mysqld_db_t /opt/netapp/data`

. Starten Sie den MySQL-Dienst:
+
`systemctl start mysqld`

. Nachdem der MySQL-Dienst gestartet wurde, starten sie die ocie- und ocieau-Dienste in der folgenden Reihenfolge:
+
`systemctl start ocie ocieau`

. Nachdem alle Dienste gestartet wurden, löschen Sie den Sicherungsordner `/backup-data`:
+
`rm -rf /backup-data`


