---
permalink: install-vapp/qsg-vapp.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, VMWare QSG, vApp QSG, quick installation 
summary: Kurzanleitung für Unified Manager auf VMware vSphere Plattform. 
---
= Schnellstartanleitung für VMware Installationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Datei herunterladen `.tar`, die ein Stammzertifikat, eine Datei und eine `OVA` Datei enthält `README`, und Unified Manager als virtuelle Appliance bereitstellen.



== Systemanforderungen

* Betriebssystem: VMware ESXi 7.0 und 8.0
* RAM: 12 GB
* CPU: Insgesamt 9572 MHz
* Freier Speicherplatz: 5 GB (Thin Provisioning), 152 GB (Thick Provisioning)


Detaillierte Informationen zu den Systemanforderungen finden Sie im link:../install-vapp/concept_requirements_for_installing_unified_manager.html["Anforderungen für die Installation von Unified Manager"] und link:http://mysupport.netapp.com/matrix["Interoperabilitätsmatrix"].



== Active IQ Unified Manager wird installiert



=== Laden Sie das Installationsprogramm herunter

. Laden Sie die Datei herunter `.tar`, die ein Stammzertifikat, eine Datei und eine `OVA` Datei enthält `README`.
. Speichern Sie die Datei in einem lokalen Verzeichnis oder Netzwerkverzeichnis, auf das Ihr vSphere Client zugreifen kann.
. Geben Sie im Verzeichnis, in das Sie die Datei heruntergeladen `.tar` haben, den Befehl ein `tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz`. + die erforderliche `OVA` Datei, ein Stammzertifikat und eine `README` Datei werden in das Zielverzeichnis entpackt.




=== Überprüfen Sie die Integrität

Sie können die Integrität der Datei überprüfen `OVA`, indem Sie die in der Datei angegebenen Schritte `README` ausführen.



=== Installation Von Unified Manager

. Klicken Sie im vSphere-Client auf *Datei > OVF-Vorlage bereitstellen*.
. Suchen Sie die OVA-Datei und stellen Sie die virtuelle Appliance mithilfe des Assistenten auf dem ESXi-Server bereit.
. Auf der Seite „Prüfungsdetails“ im Abschnitt „Herausgeber“ bestätigt die Meldung  `Entrust Code Signing - OVCS2 (Trusted certificate)`die Integrität der heruntergeladenen `OVA` Datei. Aktualisieren Sie für die Meldung `Entrust Code Signing - OVCS2 (Invalid certificate)` den VMware vCenter Server auf die Version 7.0U3E oder höher.
. Füllen Sie auf der Seite Vorlage anpassen auf der Registerkarte Eigenschaften die Felder aus, die für den Installationstyp erforderlich sind:
+
** Geben Sie für die statische Konfiguration die erforderlichen Informationen in alle Felder ein. Das Hinzufügen von Informationen für das Feld *Secondary DNS* ist nicht erforderlich.
** Wenn DHCP unter IPv4 verwendet wird, fügen Sie in keinem Feld Informationen hinzu.
** Aktivieren Sie für DHCP unter Verwendung von IPv6 das Kontrollkästchen „Automatische IPv6-Adresse aktivieren“. Fügen Sie in keinem anderen Feld Informationen hinzu.


. Schalten Sie die VM ein.
. Klicken Sie auf die Registerkarte Konsole, um den anfänglichen Startvorgang anzuzeigen.
. Zeitzone konfigurieren.
. Geben Sie einen Benutzernamen und ein Passwort für die Unified Manager-Wartung ein.


Am Ende der Installation werden die Informationen zur Verbindung mit der Unified Manager Web-Benutzeroberfläche angezeigt.
